name: Xcode - Build, Analyze and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build, analyze and test default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build, Analyze and Test
        run: xcodebuild clean build analyze test -project ACActionCable.xcodeproj -scheme ACActionCable-Package | xcpretty && exit ${PIPESTATUS[0]}
      - name: Test only
        run: xcodebuild clean test -project ACActionCable.xcodeproj -scheme ACActionCable-Package | xcpretty && exit ${PIPESTATUS[0]}
